### ISSUE TITLE
Can't connect...

### ISSUE THREAD

**Issue by Issue-has-appeared** [playingoDEERUX/growbrewproxy#11]
Hi,

I can't connect the proxy to Growtopia Private Server.

I open the Growbrew proxy, i enter IP: 13.76.248.122, Port: 17126, (i also tried 80) in the Main page i click on update IP/Port and try to connect Growtopia. But i always stuck on Located server, connecting... What i'm doing wrong? I tried 17126 and 80 ports, i even spoofed version to 3.36, 3.33 (default), etc. But i still can't connect.

**Comment by kalari123** [comment]
how to fix the error

**Comment by playingoDEERUX** [comment]
Is the server even up?

**Comment by playingoDEERUX** [comment]
Not all servers run on the same port (12126), and 80 is the http port, so it wont be the actual game serve, there is a meta data website that growtopia goes to first, which I will show you:
![image](https://user-images.githubusercontent.com/62474734/82259608-2f6dfe00-995c-11ea-9f1a-8bc37aa16fd8.png)
This is the actual game server IP and port, try connecting to that one using proxy.

**Comment by kalari123** [comment]
> 12126
I have problem when i press start http server it says something like process is already running then it says cant use the object system.net.httplistener

**Comment by Issue-has-appeared** [comment]
@playingoDEERUX Yeah it worked this time, but when i press on "Connect" button, it just stucks at Logging on MyNick... and it can't be loaded. I checked, the server is up. I spoofed GT version and did everything else. I get that 
`A new client connected from {0} 127.0.0.1:64886
Connecting to gt servers...
The growtopia client just connected successfully.
Sent logon packet!
An internal disconnection was triggered in the proxy, you may want to reconnect your GT Client if you are not being disconnected by default (maybe because of sub-server switching?)`
When i try to connect. What do i do?

**Comment by playingoDEERUX** [comment]
Maybe the server detects the proxy or something... Try another one...
I'll look at this too...

**Comment by Issue-has-appeared** [comment]
@playingoDEERUX I tried 20+ private servers that i got in my Discord, between 100 and 1k members, and all isn't worked. I just stuck on logging on MyNick... and that's it. I can't connect. I even did the IP/Growtopia/server_data.php to check port. But still the same thing happens.

**Comment by Issue-has-appeared** [comment]
@playingoDEERUX I figured something out. If i go to IP/growtopia/server_data.php, and if i see like `server|13.76.248.122 port|17091 type|1 #maint|Mainetrance message (Not used for now) -- Growtopia Noobs beta_server|127.0.0.1 beta_port|17091 beta_type|1 meta|localhost RTENDMARKERBS1001` it won't work. If i see like
`server|176.31.253.203
port|17092
type|1
#maint|Mainetrance message

beta_server|127.0.0.1
beta_port|17096

beta_type|1
meta|localhost
RTENDMARKERBS1001`

It will work. For me it worked. Most of the servers have the first variant. Is there any fix for that?

**Comment by DrOreo002** [comment]
@Issue-has-appeared oo thats a cool finding there, would be very easy to fix. Just host server_data.php on your own machine that contains the same data as their server

**Comment by Issue-has-appeared** [comment]
@DrOreo002 I got only 2 servers which have the 2nd variant i posted before, on all others servers it won't work because more than half of them have the first variant.

**Comment by DrOreo002** [comment]
> @DrOreo002 I got only 2 servers which have the 2nd variant i posted before, on all others servers it won't work because more than half of them have the first variant.

Hmmmm I don't think those server_data is the case..., proxy directly connect into the server_data.php's defined IP and port it should only host http server that point into the localhost enet server. So basically the client doesn't do any server_data request again.

**Comment by Issue-has-appeared** [comment]
@DrOreo002 But still... I tested over 30+ different servers that i have been joined in my Discord, and i only can connect to the second variant, so in my case, i can connect to only 2 servers that i got, all others wasn't working. I checked all servers...

**Comment by DrOreo002** [comment]
Yeah it does work, but I doubt that its because of the server__data.php..., since there's no known packet for the client to request it nor the server to send it. And proxy directly connect into the ip that specified at server_data.php.. basically client will never be able to get the target server's server data, also growtopia has the first variant of server data (space only, no new line) and it works fine with proxy or bot.

**Comment by playingoDEERUX** [comment]
I think I'll add some kind of autofetcher for the server meta data in server_data.php
I'll close this issue for now, if you got any more issues you can go ahead and report so :)

**Comment by DrOreo002** [comment]
> I think I'll add some kind of autofetcher for the server meta data in server_data.php
> I'll close this issue for now, if you got any more issues you can go ahead and report so :)

Hmm don't your proxy directly connect into the specified IP? without letting the client get server_data.php from the target server?
