### ISSUE TITLE
HTTP listening error

### ISSUE THREAD

**Issue by kalari123** [playingoDEERUX/growbrewproxy#12]
I have added 127.0.0.1 growtopia1.com and 127.0.0.1 growtopia2.com in host file.
(amas proxy currently working)
i heard this isfaster and wanted to try but
when i press a start http listening it gives me first this error
https://gyazo.com/b6fef5a935eef1acf4204df5872a3afc
then when i press again it gives this
https://gyazo.com/693d355bd938a9f48e870aae53871099
I have allowed it on firewall rules but idk whatswrong

**Comment by GuckTubeYT** [comment]
run as administrator

**Comment by kalari123** [comment]
> run as administrator
I have runned it with adminstrator not work

**Comment by playingoDEERUX** [comment]
@kalari123 Can you try to please run it while debugging, then clicking continue and show me the results in the visual studio IDE (in the code) ?

**Comment by kalari123** [comment]
> @kalari123 Can you try to please run it while debugging, then clicking continue and show me the results in the visual studio IDE (in the code) ?

got it working :)

**Comment by playingoDEERUX** [comment]
nice, can you give me your feedback about the proxy that we made before I close this issue sir?

**Comment by GuckTubeYT** [comment]
> nice, can you give me your feedback about the proxy that we made before I close this issue sir?

Your proxy is very good

**Comment by playingoDEERUX** [comment]
Thanks for the feedback! Closing issue...
