### ISSUE TITLE
Nothing Happened when i send Action

### ISSUE THREAD

**Issue by GuckTubeYT** [playingoDEERUX/growbrewproxy#13]
When i try to action|enter_game
and then i press send action
nothing happen

**Comment by playingoDEERUX** [comment]
Hello! Can I please know if you sent a **game** packet action (message type 3) or a **GENERIC TEXT** packet action (type 2)
Try both and also try putting a new line in the end by just adding a line space after action|enter_game (hit ENTER once)

**Comment by GuckTubeYT** [comment]
> Hello! Can I please know if you sent a **game** packet action (message type 3) or a **GENERIC TEXT** packet action (type 2)
> Try both and also try putting a new line in the end by just adding a line space after action|enter_game (hit ENTER once)

okay thanks
