### ISSUE TITLE
An internal disconnection was triggered in the proxy, you may want to reconnect your GT Client if you are not being disconnected by default (maybe because of sub-server switching?)

### ISSUE THREAD

**Issue by GuckTubeYT** [playingoDEERUX/growbrewproxy#15]
how to fix that? when i try at private server = An internal disconnection was triggered in the proxy, you may want to reconnect your GT Client if you are not being disconnected by default (maybe because of sub-server switching?)

**Comment by playingoDEERUX** [comment]
(I AM NOT ENTIRELY SURE) But if you are stuck on Located server, connecting: That could also mean that you have added the wrong IP address of the actual ENet server that you can find in server_data.php (some ppl have other port than 17091 or other ip and they only use the http server for their texture files and redirection)
I will add http client that makes a post request to get the data / fetch it from the http server so you can autograb it.

**Comment by GuckTubeYT** [comment]
not that

**Comment by GuckTubeYT** [comment]
im stuck at Logging on
and then on the logs = An internal disconnection was triggered in the proxy, you may want to reconnect your GT Client if you are not being disconnected by default (maybe because of sub-server switching?)
not stuck on located server

**Comment by playingoDEERUX** [comment]
Then it could be that the server has some simple "meta|" protection, you can bypass that by just going to their website or if you wanna bypass it completely you can simply use cheat engine to search for meta| and you can get the value and other values like IP and Port all the time.

**Comment by playingoDEERUX** [comment]
(that's like some custom string that gt gets from the website and includes it when it logins)

**Comment by playingoDEERUX** [comment]
I hope it was just like I said that the server had this kind of protection and I now favour to close this issue. Thanks.

**Comment by GuckTubeYT** [comment]
thanks

**Comment by zeejzath** [comment]
help to fix me too
