### ISSUE TITLE
GROWBREW PROXY V2 PREVIEW (Huge update coming soon!)

### ISSUE THREAD

**Issue by playingoDEERUX** [playingoDEERUX/growbrewproxy#17]
![image](https://user-images.githubusercontent.com/62474734/84494350-a1124100-aca9-11ea-954f-68bb0e5ca461.png)

![image](https://user-images.githubusercontent.com/62474734/84494403-bab38880-aca9-11ea-8af5-a6b4f6838165.png)

The HNetwork will be replaced with something else...
If you like to support, advertise this proxy with a link to this github page. Thanks!

**Comment by playingoDEERUX** [comment]
Another INFO: Binaries will also be updated soon.

**Comment by C-r-a-n-d-s** [comment]
nice

**Comment by GuckTubeYT** [comment]
Nice
