### ISSUE TITLE
Error Connecting

### ISSUE THREAD

**Issue by Elytride** [playingoDEERUX/growbrewproxy#18]
Added 127.0.0.1 growtopia1.com and 127.0.0.1 growtopia2.com to my host file > opened growbrew proxy > started server > open growtopia > tried loggin in > "Error Connecting" > Log box shows nothing (i did not do any modification to dis)

**Comment by playingoDEERUX** [comment]
Make sure you have clicked on "Start HTTP Server" before.

**Comment by playingoDEERUX** [comment]
It should be fixed in V2 beta.

**Comment by zeejzath** [comment]
help

**Comment by zeejzath** [comment]
(PROXY) [GROWBREW SILENT RECONNECT]: Growbrew detected an unexpected disconnection silently reconnecting...

**Comment by EfeTAP** [comment]
Hello playingo. i will press to start http Server + Client when the proxy is closing and sln is cant be building. Help me pls.
