### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by WozziXD** [playingoDEERUX/growbrewproxy#19]
yea i did start http server and changed the host files, problem is that when connecting to gt it stops at "located server, connecting" also does it with the enet proxy, any way to fix?
![unknown](https://user-images.githubusercontent.com/67280681/85305448-5cf31d80-b4ad-11ea-8d2c-23ee91223ae3.png)

**Comment by qatroxx** [comment]
ip changed

**Comment by DrOreo002** [comment]
The main ip from server_data.php seems wrong, but Growtopia client is still able to connect using their back-up ip. This should be resolved by Ubisoft

**Comment by playingoDEERUX** [comment]
growtopia ip changed, I will update it soon when V2 releases.

**Comment by playingoDEERUX** [comment]
the master servers are now hosted at 213.179.209.168:17279
please change all ips in the code to that IP and port 17279

**Comment by playingoDEERUX** [comment]
It should be fixed in V2 beta.
