### ISSUE TITLE
ENet 4.0.0

### ISSUE THREAD

**Issue by moien007** [playingoDEERUX/growbrewproxy#24]
Hi, I'm the author of [ENet.Managed](https://github.com/moien007/ENet.Managed) library that you are using.
I wanted to ask you to upgrade to the latest version of the library and give feedback if possible.

Thank you.

**Comment by playingoDEERUX** [comment]
Hello, thanks a lot moien for visiting my project, before I proceed, ENet 4.0.0 keeps all protocol compatibility correct?

**Comment by moien007** [comment]
Yeah, but it's no longer thread-safe and methods like `StartServiceThread` are removed.

**Comment by playingoDEERUX** [comment]
Well, that is really unfortunate, because my code made use of StartServiceThread. What's the reason behind this? It was a smart way to not make the developer deal with thread stuff.

**Comment by moien007** [comment]
Probably I shouldn't have implemented that in the first place since it wasn't the responsibility of this library.
More importantly, the overhead of `lock`s wasn't good in single-threaded games.

**Comment by moien007** [comment]
Feel free to join to my discord server: https://discord.gg/8UtvzGE

**Comment by playingoDEERUX** [comment]
Thanks.
