### ISSUE TITLE
Don't install growbrew proxy...

### ISSUE THREAD

**Issue by demonicbae** [playingoDEERUX/growbrewproxy#26]
Excuse me Deerux but why do you place backdoor i thought you were better than that...

**Comment by demonicbae** [comment]
Ok nvm just install it it isnt virus ok

**Comment by playingoDEERUX** [comment]
Sir it is open source so if there was a backdoor you may just look at it yourself... but yeah as you realized it's not a virus :D

**Comment by CuekGaming** [comment]
> Ok nvm just install it it isnt virus ok

lol xd
