### ISSUE TITLE
A Kind Of Error

### ISSUE THREAD

**Issue by SxRnArTz** [playingoDEERUX/growbrewproxy#30]
System.IO.FileNotFoundException: 'ENet.Managed, Version=3.0.2.0, Culture=neutral, PublicKeyToken=nul
I get this what can i do?
I have installed .NET Framework tho.

**Comment by smhgtfoandstfu** [comment]
Get ENet.Managed version 3.0.2.0, isnt about .net framework.

**Comment by GuckTubeYT** [comment]
Update ENet.Managed

**Comment by SxRnArTz** [comment]
where can I get it

**Comment by SxRnArTz** [comment]
oh nvm got it

**Comment by GuckTubeYT** [comment]
From NuGet
