### ISSUE TITLE
Crashed when entering private server

### ISSUE THREAD

**Issue by BbayuGt** [playingoDEERUX/growbrewproxy#32]
When enter_game is triggered (in private server) the app crashed...

Edit : using V2 release

**Comment by playingoDEERUX** [comment]
Does this occur on older versions too?
And could you run the source code under debug and show me further information, e.g crash reason if provided or stack trace?

**Comment by BbayuGt** [comment]
@playingoDEERUX 

The app is in break mode

Exception unhandled :
System.ArgumentException: "Destination array is not long enough to copy all the items in the collection. Check array index and length

**Comment by Flips1380** [comment]
true the APP auto crash

**Comment by playingoDEERUX** [comment]
Use V2.3.1 and then go to config tab and disable 'Inventory Serialization', and it should be fixed.
