### ISSUE TITLE
Tile's X/Y Coordinates always returning 0

### ISSUE THREAD

**Issue by DefaultO** [playingoDEERUX/growbrewproxy#37]
I thought it's my matrix. But your Serialization seems to be off. Or the Update broke it (if it worked before). Haven't changed much besides changing the game version and didn't bother reversing the packets yet. Guess I will have to, to get some work done.

_Debugging is not easy when you don't want to stop running the proxy server._

            World currentWorld = MainForm.messageHandler.worldMap;

            if (currentWorld.tiles.Length > 0 || currentWorld.tiles != null)
                tiles = currentWorld.tiles;

            // Matrix of currentWorld.width (100) * currentWorld.height (60).
            array = new int[currentWorld.width, currentWorld.height];

            List<string> tileIds = new List<string>();
            foreach(Tile tile in tiles)
            {
                ...
                Console.WriteLine($"{tile.x.ToString()} {tile.y.ToString()} : {tile.fg.ToString()}/{tile.bg.ToString()}");`
                ...
            }
_The .ToString conversion is not necessary. It does it on its own. I added it for something else._

![image](https://user-images.githubusercontent.com/42414542/90392702-ac119500-e08f-11ea-8f76-5fa8edc24e63.png)

**Comment by playingoDEERUX** [comment]
The serialization is indeed outdated (very old, this proxy initially was made a half year ago under private use), try the pathfinding algorithm on simple dirt worlds thats the max where it should work otherwise try studying the serialization (its really easy to update) and add certain jumps of bytes whenever necessary or required.

**Comment by DefaultO** [comment]
Thanks for finding time to reply. Good luck with the exams. Mine weren't too bad 2 years ago. You should come through them too ^^.

Thought about going memory based, since the Tesla Project looks interesting (he had implemented the feature to read a foreground/background tile by its coordinate, and that by doing some math on the offsets). But if it's as easy as you said to fully update this project (_a lot of things still work, just nuker and rayman seem to be broken completly - didn't look much into the other things to tell you exactly_) I might as well keep it packet based.

You two codes is chaotic and I had to rename a lot of things to give it some sense. You kept using the default name (+ number) for several UI Elements. Things like button4 (which gets used for sending the action packet) & button4_1 (which was used for the private server crasher or so) were horrible to look at. I know it's planned to push a cleaned up version of it, but I guess I won't need it anymore.
