### ISSUE TITLE
Growtopiaserver

### ISSUE THREAD

**Issue by BackoftheKing** [playingoDEERUX/growbrewproxy#38]
![20200818_012427](https://user-images.githubusercontent.com/69824174/90450139-a351ab00-e0f1-11ea-81f0-389588f778a7.png)
Hello, When you will release this project i waiting for 2 month and you didn't released its fake?

**Comment by DefaultO** [comment]
Wrong repository smh. Be patient, I guess.

**Comment by BackoftheKing** [comment]
> Wrong repository smh. Be patient, I guess.

He is liar i thought deerux know code but no he just doing copy paste

**Comment by playingoDEERUX** [comment]
Hello sorry for the inconvenience, the project will probably not release at this point as I have changed my mind.
