### ISSUE TITLE
Deerux what ur discord

### ISSUE THREAD

**Issue by BackoftheKing** [playingoDEERUX/growbrewproxy#39]
??

**Comment by BackoftheKing** [comment]
I want Buy something from you With Dls

**Comment by BackoftheKing** [comment]
(secret)

**Comment by DefaultO** [comment]
@BackoftheKing 
![image](https://user-images.githubusercontent.com/42414542/90548753-b74aea80-e18d-11ea-880f-8702f9ff7a39.png)

**Comment by BackoftheKing** [comment]
Not working

18 Ağu 2020 Sal 21:02 tarihinde 0xD3F <notifications@github.com> şunu yazdı:
