### ISSUE TITLE
This Pic make me Laugh LOL

### ISSUE THREAD

**Issue by CuekGaming** [playingoDEERUX/growbrewproxy#42]
![image](https://user-images.githubusercontent.com/62921987/90723463-5108b980-e2ac-11ea-8fc9-197209e4dd86.png)
![image](https://user-images.githubusercontent.com/62921987/90723493-5a922180-e2ac-11ea-91a4-2c12093061ff.png)

"Cuek" Word is from indonesia mean = "Ignore"
if cuekYT using Cuek word on his name that mean his from indonesian

but still, im not cuekYT

**Comment by BackoftheKing** [comment]
Kralll

**Comment by iProgramMC** [comment]
Yes it's kinda dumb
