### ISSUE TITLE
Invtory items count error 

### ISSUE THREAD

**Issue by ImBusy1337** [playingoDEERUX/growbrewproxy#44]
**public void SerializePlayerInventory(byte[] inventoryData)
        {
            int invPacketSize = inventoryData.Length;
            inventory.version = inventoryData[0];
            inventory.backpackSpace = BitConverter.ToInt16(inventoryData, 1);
            int inventoryitemCount = BitConverter.ToInt16(inventoryData, 5); // trade exceeding
            inventory.items = new InventoryItem[inventoryitemCount];

            for (int i = 0; i < inventoryitemCount; i++)
            {
                int pos = 7 + i * 4;
                inventory.items[i].itemID = BitConverter.ToUInt16(inventoryData, pos);
                inventory.items[i].amount = BitConverter.ToInt16(inventoryData, pos + 2);
            }
        }**
hey this have errors somewhere because it shows me error values
https://cdn.discordapp.com/attachments/698862893042630696/756539899381022862/unknown.png

**Comment by playingoDEERUX** [comment]
eh I think this has to be updated soon. I am busy with school right now so I will look into it later.

**Comment by ImBusy1337** [comment]
i fixed it u can dm me if u want ( ImBusy#0595 )

**Comment by ImBusy1337** [comment]
i gonna try to fix dropped items serialization bcz its bored asf

> eh I think this has to be updated soon. I am busy with school right now so I will look into it later.

**Comment by playingoDEERUX** [comment]
Item serialization has to be updated for that, something I don't want to do right now...
