### ISSUE TITLE
Bypass AAP isnt working

### ISSUE THREAD

**Issue by F3R07** [playingoDEERUX/growbrewproxy#50]
Did growtopia fixed AAP bypass?

**Comment by playingoDEERUX** [comment]
set mac to 02:00:00:00:00.00
if that doesn't work, gt may have fixed this particular method and you will need the mac addresses from the people individually unless I get to know about another existing one and decide to publish it..

**Comment by F3R07** [comment]
> set mac to 02:00:00:00:00.00
> if that doesn't work, gt may have fixed this particular method and you will need the mac addresses from the people individually unless I get to know about another existing one and decide to publish it..

i set mac to 02:00:00:00:00:00 isnt work
can u fix like this channel ? https://youtu.be/MlXs4RqpgcI

**Comment by GuckTubeYT** [comment]
> Did growtopia fixed AAP bypass?

yep, its patched

**Comment by GuckTubeYT** [comment]
growtopia just block mac 02:00:00:00:00:00 so, you cant use that mac
