### ISSUE TITLE
Crashed when start HTTP server 

### ISSUE THREAD

**Issue by SOREXXX** [playingoDEERUX/growbrewproxy#58]
Help pls, proxy crashed when im start http server.

**Comment by dimasali12** [comment]
same

**Comment by playingoDEERUX** [comment]
Hello this issue will be fixed by today or tomorrow, Growtopia updated server_data.php format that's why it crashes, not because of V2.1

V2.1.1 will fix this and I have it fixed internally already, but would actually like to add a few more features too before releasing the fix/patch!
