### ISSUE TITLE
What packet to open any door :)

### ISSUE THREAD

**Issue by HertZxD** [playingoDEERUX/growbrewproxy#59]
U guys know how to Open a door with packet in Growbrew 👍

**Comment by iProgramMC** [comment]
You have to be standing near a door to open it, you can't just open any door and expect it to work. Either it says "(too far away)" or it judt straight up bans you. It would only work in a private server

**Comment by HertZxD** [comment]
> You have to be standing near a door to open it, you can't just open any door and expect it to work. Either it says "(too far away)" or it judt straight up bans you. It would only work in a private server

I know, I just wanted to enter the door, but the packet punched the door

**Comment by playingoDEERUX** [comment]
Use tile activate packet and provide proper tileX/tileY location in punchX/punchY
