### ISSUE TITLE
Error connecting wait 30 seconds

### ISSUE THREAD

**Issue by StomperN7** [playingoDEERUX/growbrewproxy#6]
When trying to connect to gt getting "error connecting 30 seconds"

**Comment by XDarkTitan** [comment]
Go here and edit this
![image](https://user-images.githubusercontent.com/34183719/81771273-1c4ece80-9515-11ea-8caa-e68827510dd9.png)
then write this
![image](https://user-images.githubusercontent.com/34183719/81771281-2244af80-9515-11ea-8d97-a2e8ed85e717.png)

**Comment by StomperN7** [comment]
> Go here and edit this
> ![image](https://user-images.githubusercontent.com/34183719/81771273-1c4ece80-9515-11ea-8caa-e68827510dd9.png)
> then write this
> ![image](https://user-images.githubusercontent.com/34183719/81771281-2244af80-9515-11ea-8d97-a2e8ed85e717.png)

i did all things, i've even tried with my own local server on xampp
Got new problem, HTTP server from proxy isn't even starting

**Comment by playingoDEERUX** [comment]
Make sure port 80 is usable and I hope this issue is resolved now.
