### ISSUE TITLE
An internal disconnection was triggered in the proxy, you may want to reconnect your GT Client if you are not being disconnected by default (maybe because of sub-server switching?)

### ISSUE THREAD

**Issue by zeejzath** [playingoDEERUX/growbrewproxy#65]
An internal disconnection was triggered in the proxy, you may want to reconnect your GT Client if you are not being disconnected by default (maybe because of sub-server switching?)

how to fix ?

**Comment by playingoDEERUX** [comment]
Fixed, look at new version.
