### ISSUE TITLE
Ubisoft has changed the ENet lib used in GT

### ISSUE THREAD

**Issue by iProgramMC** [playingoDEERUX/growbrewproxy#67]
Hey everyone,

Growtopia has an updated ENet library. The most notable changes are it added IPV6 support, and it's added some stuff so you cannot connect with proxy anymore. There's a flag that disables that, however it's in the server data, and there's no way to tell the GT server that we want the old way.

Private servers still work, because the *protocol* itself isn't updated (just keep `type2` at 0 in your serverdata), but proxies and bots do not work on real GT anymore.

**Comment by Zynaty** [comment]
For those of you who still didn't fix it:
Here's a "fixed" ENet.Manged that uses @atipls's solution [from here](https://github.com/ama6nen/enetproxy/commit/7a52ee7b16e9b4824b1e1bbe349676a81945059b):
https://anonfiles.com/f6Yacd3dp4/ENet.Managed_dll

To add it just right click on the project's references and click "Add reference" and select the file (and remove the old ENet.Managed from nuget packages manager).

To connect to growtopia's servers just pass true to the "isUsingNewPacket" parameter in the CreateHost function, this will indicate that you want to use the new packet system and will allow you to connect to growtopia's servers.

Example: 
`cs
            gtServerHost = new ENetHost(
                    null, /*we only use it to connect, so no endpoint*/
                    69, /*maximum amount of peers, one per client*/
                    1, /*channel limit*/
                    0, /*unlimited incoming bandwidth*/
                    0, /*unlimited outgoing bandwith*/
                    true /*its connecting to gt's servers with the new packets so "true" is required for it to work*/);
`
Note: only pass true for the host that's connecting to gt's servers, passing it to the proxy's host will result in not receiving connections from the gt client.

**Comment by iProgramMC** [comment]
I will be checking the dll soon for malware, please be patient

**Comment by iProgramMC** [comment]
Um, no, thats not how it works.

**Comment by playingoDEERUX** [comment]
Provide the source code next time so we can verify whether it works or not, please only in form of .cs files that have changed/been modified, no .sln/vcxproj files.

**Comment by playingoDEERUX** [comment]
@Zynaty  Provide the source code next time so we can verify whether it works or not, please only in form of .cs files that have changed/been modified, no .sln/vcxproj files.

**Comment by Zynaty** [comment]
nvm skids, I'm not gonna waste time on this

**Comment by iProgramMC** [comment]
its probably just malware, removing soon

**Comment by yEsPaP** [comment]
https://github.com/ama6nen/enetproxy/commit/7a52ee7b16e9b4824b1e1bbe349676a81945059b

this guy fixed it

**Comment by playingoDEERUX** [comment]
Fixed. look at new version.
