### ISSUE TITLE
Growbrew is closing

### ISSUE THREAD

**Issue by Issue-has-appeared** [playingoDEERUX/growbrewproxy#7]
I write 127.0.0.1 growtopia1(2).com in hosts file, open Growbrew, i change "spoof growtopia version" to 3.36, i change mac, i click on "Start the proxy" and on Start HTTP Server. But after clicking start http server, it automatically closes. Any help?

**Comment by playingoDEERUX** [comment]
Please make sure port 80 is available to use.

**Comment by Issue-has-appeared** [comment]
@playingoDEERUX How can i connect in the Growtopia Private Server using (through) proxy?

**Comment by Issue-has-appeared** [comment]
Moved to #8
