### ISSUE TITLE
Source code for fixed enet.dll

### ISSUE THREAD

**Issue by programmer223** [playingoDEERUX/growbrewproxy#71]
Can u please include the source code for fixed version of enet.dll, would like to compile it myself. Thanks

**Comment by playingoDEERUX** [comment]
I have promised not to release source code of it on my own to mar4ello6,
heres virustotal results for it though:
https://www.virustotal.com/gui/file/460b4bcccb5a611b1d2aba09e8a3242ec10b0aeee31d33bf2b2b6e71a39e9051/detection
