### ISSUE TITLE
Banning when logging in with proxy 

### ISSUE THREAD

**Issue by SerpentDEV** [playingoDEERUX/growbrewproxy#74]
![image](https://user-images.githubusercontent.com/77283926/106017244-2bcc7280-60b8-11eb-9115-a905e81be73d.png)
@playingoDEERUX

**Comment by playingoDEERUX** [comment]
For 3 days? Did you use V2.3.1 or V2.3?

**Comment by SerpentDEV** [comment]
2.3 because i need drop entire inventory and theres not found resx files when you try to compile it.

**Comment by playingoDEERUX** [comment]
2.3 has this issue, it should be resolved in V2.3.1 
Not talking abou V2.2.1, I just made a NEW fix to to in 2.3.1 that wasn't a typo.

**Comment by SerpentDEV** [comment]
i found an fix somehow the super speed is toggled even if you dont toggle it. when you toggle and untoggle it fixes the problem

**Comment by playingoDEERUX** [comment]
That is super weird, I'll be taking a look at it and fix it if its making issues for me too, along with perhaps more features...

**Comment by SerpentDEV** [comment]
@playingoDEERUX  can you show me what format does account checker use in the files i did not understand the easy help

**Comment by playingoDEERUX** [comment]
Like this:

tankIDName|growid\n
tankIDPass|pass\n
