### ISSUE TITLE
multibot not works

### ISSUE THREAD

**Issue by TheLenx** [playingoDEERUX/growbrewproxy#76]
not works

**Comment by HertZxD** [comment]
hey, u need to buy the multibot to use it 
its on Growbrew Proxy "Extreame Edition"

**Comment by playingoDEERUX** [comment]
if interested dm me DEERUX#1551 i take 20e for the full extreme version lifetime or 29dls

**Comment by kuy71kuy** [comment]
are you still selling the full extreme version? i cannot dm your discord
