### ISSUE TITLE
Connect to Growtopia Private server using (through) proxy

### ISSUE THREAD

**Issue by Issue-has-appeared** [playingoDEERUX/growbrewproxy#8]
Hello,

How i can connect to Growtopia Private server using (through) proxy?

Thanks.

**Comment by playingoDEERUX** [comment]
Get the ENet's Server IP and Port then just change it in the menu, getting the ip/port has several ways of doing that which none actually has to do with the growbrew proxy itself though. If the server is down, it won't connect.
