### ISSUE TITLE
(FIXED) Done building project "GrowbrewProxy.csproj" -- FAILED.

### ISSUE THREAD

**Issue by Desync3** [playingoDEERUX/growbrewproxy#83]
I need help i get this problem while trying to build the project!!!

**Comment by majknez** [comment]
Check if there is any output file in the release folder and we are lacking information there might be errrors etc

**Comment by Desync3** [comment]
> Check if there is any output file in the release folder and we are lacking information there might be errrors etc

I removed everything there and tried again same error, If you wouldn\t mind could you add me on discord because you could help me easier there :). "Desync#3761"

**Comment by majknez** [comment]
Added you on discord

**Comment by majknez** [comment]
U can close the issue fixed now
