### ISSUE TITLE
System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by StomperN7** [playingoDEERUX/growbrewproxy#9]
System.PlatformNotSupportedException in System.Net.HttpListener..ctor()
Getting this error after staring HTTP server.
Using VS 2019 and Windows 8.1 x64

**Comment by playingoDEERUX** [comment]
Hello! Your platform might not be supported What you can also do is using a seperate HTTP server (python script, XAMPP (apache) or nginx) so growtopia gets that data to connect to the proxy.
When you did that, make sure you create a folder called "growtopia" in the folder where your system accesses the website and in there is must be a file called "server_data.php" with this text below:

---------------------------------------------
server|127.0.0.1
port|2
beta_server|127.0.0.1
beta_port|2
meta|growmmfi.de
RTENDMARKERBS1001
---------------------------------------------

(dont copy the minuses) After growtopia receives this in any form by http server, it will connect to the proxy if the proxy is running!

**Comment by playingoDEERUX** [comment]
server|127.0.0.1
port|2
beta_server|127.0.0.1
beta_port|2
meta|growmmfi.de
RTENDMARKERBS1001

**Comment by StomperN7** [comment]
Thanks
