### ISSUE TITLE
not working <3

### ISSUE THREAD

**Issue by vietor55** [playingoDEERUX/growbrewproxy#90]
added hosts
started as administrator
changed spoof
started http
started proxy

and growtopia is still  running normally, like theres no proxy running.

thanks for your advices

**Comment by codeszsoft** [comment]
growtopia 3.95 need SSL for the HTTPS

**Comment by Gorkido** [comment]
> added hosts started as administrator changed spoof started http started proxy
> 
> and growtopia is still running normally, like theres no proxy running.
> 
> thanks for your advices

Same here

https://user-images.githubusercontent.com/81165187/197282311-01788aa8-de54-4439-899f-cdcaf0d796b4.mp4

**Comment by DugorClient** [comment]
@Gorkido  Failed to load ENet dynamic library. (Native last error: 0).
cloud you help me i dont understand what i did wrong

**Comment by majknez** [comment]
> 

you need to have the enet library otherwise u cant run.

**Comment by DugorClient** [comment]
where i can download it?

**Comment by DugorClient** [comment]
@actuallydoc

**Comment by Gorkido** [comment]
> where i can download it?

https://github.com/moien007/ENet.Managed

1. Download its [source](https://github.com/moien007/ENet.Managed/archive/refs/heads/master.zip)
2. Extract it.
3. Copy `\ENet.Managed\src\ENet.Managed\` to `\growbrewproxy-master\GrowbrewProxy\` (first delete existing ENet.Managed folder)
4. Try to build GrowbrewProxy (you'll prob see an error. Explained [here](https://github.com/playingoDEERUX/growbrewproxy/issues/91).

**Comment by Lebedev21** [comment]
> > where i can download it?
> 
> https://github.com/moien007/ENet.Managed
> 
> 1. Download its [source](https://github.com/moien007/ENet.Managed/archive/refs/heads/master.zip)
> 2. Extract it.
> 3. Copy `\ENet.Managed\src\ENet.Managed\` to `\growbrewproxy-master\GrowbrewProxy\` (first delete existing ENet.Managed folder)
> 4. Try to build GrowbrewProxy (you'll prob see an error. Explained [here](https://github.com/playingoDEERUX/growbrewproxy/issues/91).

Well... How do I fix the error?

**Comment by emeryhyden** [comment]
> > where i can download it?
> 
> https://github.com/moien007/ENet.Managed
> 
>     1. Download its [source](https://github.com/moien007/ENet.Managed/archive/refs/heads/master.zip)
> 
>     2. Extract it.
> 
>     3. Copy `\ENet.Managed\src\ENet.Managed\` to `\growbrewproxy-master\GrowbrewProxy\` (first delete existing ENet.Managed folder)
> 
>     4. Try to build GrowbrewProxy (you'll prob see an error. Explained [here](https://github.com/playingoDEERUX/growbrewproxy/issues/91).

Very helpful. How do you fix the error then?? What have we accomplished??

**Comment by iProgramMC** [comment]
Growbrew Proxy is abandonware. We will not continue updating this software, it is up to you to update it if you so choose. If you can create an HTTPS server which Growtopia will happily connect to, be sure to make a fork and let other people use it. :)
